name: Build and Release

on:
  push:
    tags:
      - "v*"  # Запуск при создании тега (например, v1.0, v2.3.4)

jobs:
  build:
    runs-on: windows-latest  # Сборка под Windows (для .exe)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller --onefile --windowed src/main.py

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe  # Путь к EXE-файлу
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен доступа